application.run_initial_import=true
application.run_initial_update=true
application.run_vector_images_update=false


application.authentication.user=uptempo-shutterstock-import
application.authentication.password=dsfoOd/d&ew(freui9tjdUfw=(r4giedefr

    
application.server.url=https://mediaservices-test.zf.com/
application.server.soap_url=https://mediaservices-test.zf.com/webservices/MediaPool/
application.server.request_timeout=60
application.server.max_in_memory_size=1000000000
application.server.port=8080

application.mp.web.cookie=JSESSIONID=r7SKYm1IvQsUCJoXkl3Cgc0d9Ne0LhwmWNCzDvWl.e47923f84117; JSESSIONIDSSO=MrTZQmeNJOQ2QdoiOA1WnLptv9S6akWV-8PDEdN9; JSESSIONID_MMS=r7SKYm1IvQsUCJoXkl3Cgc0d9Ne0LhwmWNCzDvWl
application.mp.web.referer=https://mediaservices-test.zf.com/web/mp/search