application:

  run_initial_import: true
  run_initial_update: true
  run_vector_images_update: true

  authentication:
    user: uptempo-shutterstock-import
    password: dsfoOd/d&ew(freui9tjdUfw=(r4giedefr

  server:
    url: https://mediaservices-test.zf.com/
    soap_url: https://mediaservices-test.zf.com/webservices/MediaPool/
    request_timeout: 60
    max_in_memory_size: 1000000000
    port: 8080